import { UnitType, UnitConfig } from '../types/game';

export const UNIT_CONFIGS: Record<UnitType, UnitConfig> = {
  archer: {
    name: '궁수',
    emoji: '🏹',
    description: '원거리 공격의 달인\n높은 데미지, 중간 사거리',
    baseHealth: 80,
    baseDamage: 25,
    attackRange: 200,
    attackSpeed: 1200,
    cost: 30,
  },
  wizard: {
    name: '마법사',
    emoji: '🧙',
    description: '범위 마법 공격\n느린 공격속도, 높은 데미지',
    baseHealth: 60,
    baseDamage: 40,
    attackRange: 250,
    attackSpeed: 2000,
    cost: 50,
  },
  tank: {
    name: '탱커',
    emoji: '🛡️',
    description: '몬스터 속도 감소\n높은 체력, 근접 공격',
    baseHealth: 200,
    baseDamage: 15,
    attackRange: 80,
    attackSpeed: 1500,
    cost: 40,
  },
  healer: {
    name: '힐러',
    emoji: '✨',
    description: '아군 유닛 회복\n약한 공격력, 지원형',
    baseHealth: 70,
    baseDamage: 10,
    attackRange: 150,
    attackSpeed: 1800,
    cost: 35,
  },
  assassin: {
    name: '암살자',
    emoji: '🗡️',
    description: '빠른 연속 공격\n낮은 데미지, 빠른 속도',
    baseHealth: 50,
    baseDamage: 12,
    attackRange: 120,
    attackSpeed: 400,
    cost: 25,
  },
};
